# Generated by Django 2.0.9 on 2019-05-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0003_horse_post_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='odds',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
