# Generated by Django 2.0.9 on 2019-05-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0006_horse_disqualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='program_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
