# Generated by Django 2.0.9 on 2019-05-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0008_stable_is_valid_at_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='scratched_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
