# Generated by Django 2.0.9 on 2019-06-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0009_horse_scratched_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
