# Generated by Django 2.0.9 on 2019-06-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0012_auto_20190603_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='coupled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horse',
            name='coupled_indicator',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
