# Generated by Django 2.0.9 on 2019-06-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0014_auto_20190608_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='stable',
            name='stable_count_at_finish',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
