# Generated by Django 2.0.9 on 2019-06-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0002_racecard_races'),
        ('stables', '0015_stable_stable_count_at_finish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horse',
            new_name='Runner',
        ),
    ]
