# Generated by Django 2.0.9 on 2019-11-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0017_auto_20190628_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stable',
            name='is_valid_at_start',
            field=models.NullBooleanField(db_index=True),
        ),
    ]
