# Generated by Django 2.0.9 on 2019-11-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0018_auto_20191101_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='owner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
