# Generated by Django 2.0.9 on 2023-06-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0026_stable_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='stable',
            name='replaced_scratches_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
