# Generated by Django 2.0.9 on 2019-10-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_notification_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='game',
            name='winner_limit',
            field=models.IntegerField(default=1),
        ),
    ]
