# Generated by Django 2.0.9 on 2019-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20191031_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stable_limit',
            field=models.IntegerField(default=1),
        ),
    ]
