# Generated by Django 2.0.9 on 2019-12-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_stable_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='entry_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='runner_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='salary_cap',
            field=models.IntegerField(default=50000),
        ),
    ]
