# Generated by Django 2.0.9 on 2020-04-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20191207_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stable_limit',
            field=models.IntegerField(default=-1),
        ),
    ]
