# Generated by Django 2.0.9 on 2020-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200422_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='commission_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='contest_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
