# Generated by Django 2.0.9 on 2023-04-13 10:50

from django.db import migrations, models
import django.db.models.deletion
import games.models
import games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20210111_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('link', models.CharField(blank=True, max_length=256)),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to=games.models.Banner_Images, validators=[games.validators.validate_banner_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
