# Generated by Django 2.0.9 on 2023-04-20 12:35

from django.db import migrations, models
import games.models
import games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20230413_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Image height should not exceed 85px', upload_to=games.models.Banner_Images, validators=[games.validators.validate_banner_image]),
        ),
    ]
