# Generated by Django 2.0.9 on 2023-05-01 08:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20230420_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'a': 1}),
        ),
    ]
