# Generated by Django 2.0.9 on 2023-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20230501_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='payout_projections',
            field=models.TextField(blank=True, null=True),
        ),
    ]
