# Generated by Django 2.0.9 on 2023-08-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_gameexcludeusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1, verbose_name='Stable Position')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
    ]
