# Generated by Django 2.0.9 on 2020-04-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsepoint',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
