# Generated by Django 2.0.9 on 2020-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_points', '0003_auto_20200917_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsepoint',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
