# Generated by Django 2.0.9 on 2019-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth0_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
