# Generated by Django 2.0.9 on 2020-07-01 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagering', '0006_auto_20200701_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='stable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stables.Stable'),
        ),
    ]
