# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: ubuntu-latest

steps:

# - script: |
#     python -m pip install --upgrade pip setuptools wheel
#     pip install psycopg2-binary
#     pip install -r requirements/production.txt
#   displayName: 'Install prerequisites'
#   workingDirectory: 'djangoapp/'

- task: CopyFiles@2
  inputs:
    SourceFolder: './'
    Contents: |
      bin/**
      chef/**
      djangoapp/**
      test-files/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish DjangoApp package artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'DjangoApp'    
    publishLocation: 'Container'