# Generated by Django 2.0.9 on 2020-01-22 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='follow_id',
            new_name='horse',
        ),
        migrations.AddField(
            model_name='follows',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='follows',
            name='follow_type',
        ),
        migrations.RemoveField(
            model_name='follows',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together={('owner', 'horse')},
        ),
    ]
