# Generated by Django 2.0.9 on 2020-01-27 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0019_auto_20191108_1552'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follows', '0003_follows_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stables.Runner'),
        ),
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together={('owner', 'horse', 'user')},
        ),
    ]
