# Generated by Django 2.0.9 on 2020-01-31 23:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follows', '0006_auto_20200131_2315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together={('owner', 'horse', 'user')},
        ),
    ]
