# Generated by Django 2.0.9 on 2019-06-05 23:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racecards', '0002_racecard_races'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('ios_latest_version', models.CharField(max_length=200)),
                ('ios_required_version', models.CharField(max_length=200)),
                ('android_latest_version', models.CharField(max_length=200)),
                ('android_required_version', models.CharField(max_length=200)),
                ('racecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racecards.Racecard')),
            ],
        ),
    ]
