# Generated by Django 2.0.9 on 2019-06-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionrequirement',
            name='params',
        ),
        migrations.RemoveField(
            model_name='versionrequirement',
            name='racecard',
        ),
    ]
