# Generated by Django 2.0.9 on 2020-04-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0008_follows_horse_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='horse_point',
        ),
    ]
