# Generated by Django 2.0.9 on 2020-04-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0010_follows_horse_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='horse_point',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horse_points.HorsePoint'),
        ),
    ]
