# Generated by Django 2.0.9 on 2019-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190423_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stable_name',
            field=models.CharField(help_text='Name of the users stable', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth0_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
