# Generated by Django 2.0.9 on 2019-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190426_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(help_text='Five digit zip code or postal code', max_length=15),
        ),
    ]
