# Generated by Django 2.0.9 on 2020-06-05 17:44

import random
from django.db import migrations, models

stable_names = set()
def set_defaults(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all().iterator():
        stable_name = profile.stable_name
        while stable_name.lower() in stable_names:
            stable_name = "{}{}".format(profile.stable_name, random.randint(1,100))

        profile.stable_name = stable_name
        profile.unique_stable_name = stable_name.lower()
        stable_names.add(profile.unique_stable_name)

        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_stable_name',
            field=models.CharField(blank=True, help_text='Autoset field to ensure stable name is unique in case insensitive manner', max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(set_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='unique_stable_name',
            field=models.CharField(help_text='Autoset field to ensure stable name is unique in case insensitive manner', max_length=50, unique=True, db_index=True),
        ),
    ]
