# Generated by Django 2.0.9 on 2023-09-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_unique_stable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gamstop_exclude',
            field=models.BooleanField(default=False),
        ),
    ]
