# Generated by Django 2.0.9 on 2020-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_points', '0002_auto_20200414_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsepoint',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
