# Generated by Django 2.0.9 on 2019-12-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='stable_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
