# Generated by Django 2.0.9 on 2019-05-07 18:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racecard',
            name='races',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
