# Generated by Django 2.0.9 on 2023-04-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0005_auto_20230303_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackvideo',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trackvideo',
            name='mode',
            field=models.CharField(choices=[['ROBERTS', 'Roberts'], ['STEEPLECHASE', 'Steeplechase']], default='ROBERTS', max_length=25),
        ),
        migrations.AlterField(
            model_name='trackvideo',
            name='stream_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
