# Generated by Django 2.0.9 on 2023-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0006_auto_20230412_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='racecard',
            name='mode',
            field=models.CharField(choices=[['HARNESS', 'HARNESS'], ['THOROUGHBRED', 'THOROUGHBRED']], default='THOROUGHBRED', max_length=30),
        ),
    ]
