# Generated by Django 2.0.9 on 2023-05-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0007_racecard_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarnessTracksDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('trackmastercode', models.CharField(max_length=10, unique=True)),
                ('equibasecode', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=3)),
                ('state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('timezoneabbrev', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
