# Generated by Django 2.0.9 on 2023-05-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0008_harnesstracksdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harnesstracksdetail',
            name='country',
            field=models.CharField(max_length=10),
        ),
    ]
