# Generated by Django 2.0.9 on 2023-05-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0009_auto_20230524_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harnesstracksdetail',
            name='equibasecode',
            field=models.CharField(max_length=10),
        ),
    ]
