# Generated by Django 2.0.9 on 2023-08-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0011_auto_20230816_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackvideo',
            name='mode',
            field=models.CharField(choices=[['ROBERTS', 'Roberts'], ['STEEPLECHASE', 'Steeplechase'], ['SMS', 'SMS']], default='ROBERTS', max_length=25),
        ),
    ]
