# Generated by Django 2.0.9 on 2019-08-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0002_racecard_races'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='notable_race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='opened',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='triple_crown_winners',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
