# Generated by Django 2.0.9 on 2023-02-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0003_auto_20190807_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[['HD', 'HD'], ['SD', 'SD']], default='HD', max_length=25)),
                ('stream_name', models.CharField(max_length=200)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racecards.Track')),
            ],
        ),
    ]
