# Generated by Django 2.0.9 on 2023-08-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racecards', '0010_auto_20230524_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='PATracksDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='racecard',
            name='mode',
            field=models.CharField(choices=[['HARNESS', 'HARNESS'], ['PA', 'PA'], ['THOROUGHBRED', 'THOROUGHBRED']], default='THOROUGHBRED', max_length=30),
        ),
        migrations.AlterField(
            model_name='track',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
