# Generated by Django 2.0.9 on 2019-10-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0017_auto_20190628_1856'),
        ('stable_points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stablepoint',
            name='stable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stables.Stable'),
        ),
    ]
