# Generated by Django 2.0.9 on 2020-07-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_points', '0002_stablepoint_stable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stablepoint',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
