# Generated by Django 2.0.9 on 2020-10-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable_points', '0003_auto_20200723_0017'),
        ('stable_points', '0003_auto_20200723_0024'),
    ]

    operations = [
    ]
