# Generated by Django 2.0.9 on 2019-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0004_horse_odds'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='finish',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='lengths_ahead',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='lengths_behind',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
