# Generated by Django 2.0.9 on 2019-06-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0010_horse_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='finish',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='lengths_ahead',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='lengths_behind',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='scratched_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
