# Generated by Django 2.0.9 on 2019-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0011_auto_20190603_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
