# Generated by Django 2.0.9 on 2019-06-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0013_auto_20190604_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='stable',
            name='scratch_limit_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stable',
            name='scratches_at_finish',
            field=models.BooleanField(default=False),
        ),
    ]
