# Generated by Django 2.0.9 on 2020-02-19 13:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0019_auto_20191108_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='custom_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
    ]
