# Generated by Django 2.0.9 on 2020-04-10 14:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0021_auto_20200409_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='custom_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
