# Generated by Django 2.0.9 on 2020-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0022_auto_20200410_1426'),
    ]

    operations = [
        migrations.AddField( 
            model_name='stable',
            name='entry_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
