# Generated by Django 2.0.9 on 2023-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables', '0027_stable_replaced_scratches_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='external_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='program_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
