# Generated by Django 2.0.9 on 2019-05-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='racecards',
            new_name='racecard',
        ),
    ]
