# Generated by Django 2.0.9 on 2019-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190626_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
