# Generated by Django 2.0.9 on 2023-04-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='status',
        ),
        migrations.AddField(
            model_name='banner',
            name='visibility',
            field=models.CharField(choices=[['VISIBLE', 'Visible'], ['HIDDEN', 'Hidden']], default='VISIBLE', max_length=20),
        ),
    ]
