# Generated by Django 2.0.9 on 2023-06-26 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0018_game_payout_projections'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='private_members',
            field=models.ManyToManyField(through='games.GameUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
