# Generated by Django 2.0.9 on 2019-11-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
