# Generated by Django 2.0.9 on 2020-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_stable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='runner_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(blank=True, choices=[('scratch', 'Scratch'), ('stable_incomplete', 'Stable Incomplete'), ('first_post', 'First Post'), ('race_scores_posted', 'Race Scores Posted'), ('race_canceled', 'Race Canceled'), ('race_completed', 'Race Completed'), ('race_results_posted', 'Race Results Posted'), ('game_canceled', 'Game Canceled'), ('followed_horse', 'Followed Horse')], default=None, max_length=25, null=True),
        ),
    ]
