# Generated by Django 2.0.9 on 2020-04-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200311_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, choices=[('go_to_stable', 'Go to Stable'), ('go_to_leaderboard', 'Go to Leaderboard'), ('go_to_runner', 'Go to Runner'), ('none', 'None')], default=None, max_length=25, null=True),
        ),
    ]
