# Generated by Django 2.0.9 on 2020-05-28 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200528_1258'),
        ('stables', '0023_stable_entry_number'),
        ('wagering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chrims_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('stable', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='stables.Stable')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chrims_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('void_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chrims_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('bet', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='wagering.Bet')),
            ],
        ),
    ]
