# Generated by Django 2.0.9 on 2020-06-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagering', '0004_auto_20200619_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='stable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stables.Stable'),
        ),
    ]
