# Generated by Django 2.0.9 on 2020-07-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagering', '0005_auto_20200624_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='stable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stables.Stable'),
        ),
    ]
