# Generated by Django 2.0.9 on 2023-07-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagering', '0008_auto_20200703_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='credit',
            field=models.BooleanField(default=False),
        ),
    ]
