Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    # The AWS api forces signed requests to be no older than 5 minutes. If you leave a vagrant VM running while your
    # host OS sleeps, you can experience a drastic time skew on the guest OS.
    #
    # This forces the system time to sync every 10 seconds as opposed to the default 20 minutes.  If you still
    # experience AWS 400 errors, the solution is to run `vagrant reload`.
    v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]

    # Some host OSs have experienced read-only shared mounts.  This seems to mitigate the problem
    v.customize [ "setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1" ]
    v.customize [ "setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/home/vagrant/stableduel", "1" ]

    # Remote files seem to download slowly without these settings
    v.customize [ "modifyvm", :id, "--natdnshostresolver1", "on" ]
    v.customize [ "modifyvm", :id, "--natdnsproxy1", "on" ]
  end
  config.vm.hostname = "stableduel-berkshelf"
  config.vm.box = "ubuntu/xenial64"

  config.vm.network :forwarded_port, guest: 80, host: 8000
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 5555, host: 5555
  config.vm.network :forwarded_port, guest: 5678, host: 55678
  config.vm.boot_timeout = 120

  config.berkshelf.enabled = true
  config.omnibus.chef_version = "12.10.24"

  config.vm.synced_folder "../", "/home/vagrant/stableduel"

  # OSX needs this for concurrent open files
  config.vm.provision :shell, :inline => "ulimit -n 4048"

  # This is needed for windows 7 (not sure about later versions)
  config.vm.provision :shell, :inline => <<-SHELL
    echo 'Acquire::ForceIPv4 "true";' | tee /etc/apt/apt.conf.d/99force-ipv4
  SHELL

  config.vm.provision :chef_solo do |chef|
    chef.log_level = :fatal
    # Sets password for the postgres user
    chef.json = {
      'stableduel' => {
        'dev' => true,
        'user' => 'vagrant',
        'domain' => 'localhost:8000',
        'environment' => {
          "DATABASE_URL": "postgres://postgres:password@127.0.0.1:5432/stableduel",
          "AUTH_AUDIENCE": "http://localhost:8000",
          "AUTH_ISSUER": "https://stableduel.auth0.com/",
          "DRIP_ACCOUNT_ID": "6716313",
          "DRIP_API_TOKEN": "ad328ed679ef4f6a892c60f333754d5d",
          "TIMEFORM_URL": "https://api.timeformus.com/Services/Data/",
          "TIMEFORM_USERNAME": "stableduel",
          "TIMEFORM_PASSWORD": "rH3KFjs8WA94tPeF",
          "CHRIMS_BASE_URL": "https://stableduel-api-qa.azurewebsites.net/api/",
          "CHRIMS_SECRET": "H0m3Str3tcH!",
          "CHRIMS_AUDIT": true,
          "CHRIMS_DECRYPT": true,
          "SD_DEBUG_AUTH": true,
          "SD_DEBUG_TOKEN": "local",
          "AMPLITUDE_URL": "https://api.amplitude.com/2/httpapi",
          "AMPLITUDE_KEY": "7a23eba7167a54ced6f3715f721bf8da"
        }
      }
    }

    chef.run_list = [
       "recipe[chef-stableduel::system]",
      "recipe[chef-stableduel::server]",
      "recipe[chef-stableduel::dev_database]",
      "recipe[chef-stableduel::django]",
      "recipe[chef-stableduel::redis]",
    ]
  end
end
